### PR TITLE
feat: add existing resource options for OCP pattern

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Added existing resource optional inputs for the OCP pattern. This PR will add the options to specify an existing KMS and/or COS instance for keys and buckets, as well as some boolean inputs to direct certain aspects to use those existing resources.

The input variables have only been added to the `patters/roks` for now, but most of the work has been done in the dynamic modules to be shared by all patterns, so that these new optional inputs can be added to other patterns with less effort.

Some additional changes have also been made to the root module to better facilitate these new existing resource options, including more input options to control if service-to-service auth policies are created or not.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Have added the following optional input variables to the `patterns/roks` solution allowing the use of existing resources for KMS and COS:
- existing_kms_instance_name
- existing_kms_resource_group
- existing_kms_endpoint_type
- existing_cos_instance_name
- existing_cos_resource_group
- existing_cos_endpoint_type
- use_existing_cos_for_vpc_flowlogs
- use_existing_cos_for_atracker

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by toddgiguere** [comment]
Initial unit test run was successful, all consistency and upgrade tests have passed, so these changes are likely safe for all patterns and upgrade.

The only test failure was a timeout waiting on schematics destroy, will run pipeline again.

**Comment by vburckhardt** [comment]
May want to open an additional issue to allow passing the crn.

**Comment by vburckhardt** [comment]
Latest error 2024/08/07 20:22:24 Error getting least vpc region - may be a blip

**Comment by toddgiguere** [comment]
Only failure from most recent pipeline run was a single `Destroy` event, seeing this error again:
> [ERROR] Error Deleting resource group: Resource groups with active instances can't be deleted.

Will continue running pipeline until we can get all tests green. So far between all previous pipeline runs, every test has passed at least once, but haven't gotten them to all pass at same time.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
