### PR TITLE
feat: add support for at management events

### PR DESCRIPTION
**Pull request by kierramarie**
### Description

Provider has added support for management_events for atracker. Support for this has been added to cos.tf

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/820

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by kierramarie** [comment]
@ocofaigh we have not bumped the version of the ibm provider in the examples and patterns. should I do that?

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@kierramarie your missing some provider version updates. For example, each of the patterns have a modules folder - you going to need to update those too. Suggest to do a find for the text `required_providers` and review every file

**Comment by ocofaigh** [comment]
Will merge https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/848# first and then rebase this and merge

**Review by ocofaigh — DISMISSED** [review]

**Comment by ocofaigh** [comment]
Pipeline is hitting a few intermittent issue, so going to retry..

**Comment by ocofaigh** [comment]
@kierramarie can you resolve conflicts and lets see how tests get on

**Review by toddgiguere — APPROVED** [review]

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
