### PR TITLE
feat: v2 stencil for all-diagrams

### PR DESCRIPTION
**Pull request by alex-reiff**
### Description

Update our diagrams to use v2 stencils.

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by alex-reiff** [comment]
all-diagrams drawio

Here's the svg for the all-diagrams diagram, Figured it made more sense to pause for feedback here before I tweak this to make the rest of the diagrams.

(using old activity tracker logo as a placeholder)

**Comment by SirSpidey** [comment]
Hey @alex-reiff. Some comments.
- This is the replacement drawio file for only the `vsi-vsi.drawio.svg`, right?
- The original issue with Activity Tracker is not with the AT icon but about an icon called `Activity Tracker Cloud Object Storage`, which does not exist. See [thread](https://ibm-cloudplatform.slack.com/archives/C1UAU5NNP/p1681932255790979?thread_ts=1680495001.232119&cid=C1UAU5NNP) in #activity-tracker-user.
- I've learned that we need to set the background to white. The transparent background doesn't work when you set IBM Cloud to dark mode. 
- The final PR should have SVG images, not drawio files. Information about how to export: https://test.cloud.ibm.com/docs/writing?topic=writing-diagrams#diagrams-drawio (ignore the transparent setting)

**Comment by alex-reiff** [comment]
@SirSpidey This is currently the all-diagrams.drawio file (which is I think identical to vsi-vsi but not in svg), I will create the svgs once this looks good.

**Review by SirSpidey — CHANGES_REQUESTED** [review]
Looks great. Nice to see them all with the same left legend.
My only request is to set all diagrams with a `white` background so they show correctly in dark themes.

**Comment by alex-reiff** [comment]
@SirSpidey Is that another setting in the export? I left Transparent Background unchecked and they look fine to me in the preview,

Also noticed an issue in VPC so I'll push changes to that tomorrow.

**Comment by SirSpidey** [comment]
@alex-reiff Here's what the SVGs were looking like in the console with the dark theme before we set the background to white. 
image

It's a setting in the draw.io file itself when nothing is selected:
image

**Review by SirSpidey — APPROVED** [review]
👍 SVGs look ok to me in spot check, regardless of how they preview.

**Review by SirSpidey — APPROVED** [review]
👍 Having only svg files seems to be fine: 

> `.drawio` (default): saves your diagram in the default XML diagram data format.
> 
> `.svg`: saves your diagram as a SVG image file and embeds your diagram data. You can use it as an SVG image, but also load the SVG file into draw.io and edit it as if it were a diagram file.
from https://www.drawio.com/doc/faq/save-file-formats.

**Pull request merged**
