### PR TITLE
feat: add support for VNI in vsi module

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
I guess we need to consider how this impact the migration script from v5 -> v6 as user would also have to set the boolean to continue on the legacy, otherwise migration is pointless right?

**Comment by Aashiq-J** [comment]
Yep, we want the new customers to use the new VNI so we can't set `use_legacy_network_interface` to true.
We might want to document in the migration process that they will need to set the `use_legacy_network_interface` to true while upgrading.

**Comment by Aashiq-J** [comment]
Screenshot 2024-11-13 at 9 46 32 AM
Screenshot 2024-11-13 at 9 46 41 AM
Tests which failed in pipeline passes when we set `use_legacy_network_interface ` to true.
We will need to skip the upgrade test since we have `use_legacy_network_interface` as `false` by default.

**Pull request merged**
