### PR TITLE
feat: added public service endpint url for the cluster

### PR DESCRIPTION
**Pull request by rajatagarwal-ibm**
### Description

Add cluster URL output to Red Hat OpenShift Container Platform on VPC landing zone

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
Some testing is still pending - please do not review.

**Comment by rajatagarwal-ibm** [comment]
Output 

```
workload_cluster_id = "cr3gsrqd0krk13m3mud0"
workload_cluster_ingress_hostname = "rajat-roksqs-workload-clu-3b5bf5f75003778663c521c8c35ad277-0000.us-south.containers.appdomain.cloud"
workload_cluster_private_service_endpoint_url = "https://c100.private.us-south.containers.cloud.ibm.com:32110"
workload_cluster_public_cluster_url = "https://console-openshift-console.rajat-roksqs-workload-clu-3b5bf5f75003778663c521c8c35ad277-0000.us-south.containers.appdomain.cloud"
workload_cluster_public_service_endpoint_url = "https://c100-e.us-south.containers.cloud.ibm.com:32110"
```

**Review by toddgiguere — CHANGES_REQUESTED** [review]

**Comment by rajatagarwal-ibm** [comment]
**Updated output -** 

```
workload_cluster_console_url = "https://console-openshift-console.rajat-roksqs-workload-clu-3b5bf5f75003778663c521c8c35ad277-0000.us-south.containers.appdomain.cloud"
workload_cluster_id = "cr3gsrqd0krk13m3mud0"
workload_cluster_ingress_hostname = "rajat-roksqs-workload-clu-3b5bf5f75003778663c521c8c35ad277-0000.us-south.containers.appdomain.cloud"
workload_cluster_private_service_endpoint_url = "https://c100.private.us-south.containers.cloud.ibm.com:32110"
workload_cluster_public_service_endpoint_url = "https://c100-e.us-south.containers.cloud.ibm.com:32110"
```

**Comment by rajatagarwal-ibm** [comment]
Getting this error as `public_service_endpoint_url` is returning   an "" empty string rather than null value. Updated the code to handle the scenario

```
2024-08-26T10:11:02.4167399Z TestRunUpgradeRoksPattern 
2024-08-26T10:11:02Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1;
2024-08-26T10:11:02.4170135Z Error: Error in function call
2024-08-26T10:11:02.4174135Z   on ../../outputs.tf line 99, in output "cluster_data":
2024-08-26T10:11:02.4175604Z   99:       public_service_endpoint_url = coalesce(cluster.public_service_endpoint_url, null)
2024-08-26T10:11:02.4177261Z       │ cluster.public_service_endpoint_url is ""
2024-08-26T10:11:02.4190151Z Call to function "coalesce" failed: no non-null, non-empty-string arguments.
2024-08-26T10:11:02.4196012Z Error: Error in function call
2024-08-26T10:11:02.4197467Z   on ../../outputs.tf line 99, in output "cluster_data":
2024-08-26T10:11:02.4198443Z   99:       public_service_endpoint_url = coalesce(cluster.public_service_endpoint_url, null)
2024-08-26T10:11:02.4199995Z       │ cluster.public_service_endpoint_url is ""
2024-08-26T10:11:02.4201232Z Call to function "coalesce" failed: no non-null, non-empty-string arguments.
}

```

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
