### PR TITLE
fix: upgrade to vpc module v7.5.0

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Upgrade to `terraform-ibm-landing-zone-vpc` module to v7.5.0, which includes a change to clean (empty) the default VPC Security Group and ACL so that they will not have any rules.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

This release includes an upgrade to the `terraform-ibm-landing-zone-vpc` module (v7.5.0) which changed how the default VPC Security Group and ACL can be cleaned of rules (less permissive).
[terraform-ibm-landing-zone-vpc v7.5.0](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/releases/tag/v7.5.0)

The VPC module upgrade has changed the inputs required to clean the sg/acl and this release of landing zone also incorporates the following changes:
- REMOVED: clean_default_security_group and clean_default_acl from VPC configuration
- ADDED: clean_default_sg_acl to VPC configuration

Upgrade Notes:
After upgrade to this version, you may notice the following resources are marked for `destroy` during your next `terraform plan` phase. This is expected, as we have retired the scripts that were executed by these `null_resource` blocks and they are not needed.
```
module.landing_zone.module.vpc["management"].null_resource.clean_default_acl[0] will be destroyed
module.landing_zone.module.vpc["management"].null_resource.clean_default_security_group[0] will be destroyed
```

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by ocofaigh** [comment]
@toddgiguere upgrade tests failing but I think they are expected. I'll let you take a look to confirm

**Comment by toddgiguere** [comment]
Upgrade tests for all 4 patterns has failed, which was expected due to changes in the VPC module.

Each pattern test upgrade had the same 4 resources marked for destroy after upgrade:
- module.landing_zone.module.landing_zone.module.vpc["management"].null_resource.clean_default_security_group[0] Actions: [delete]
- module.landing_zone.module.landing_zone.module.vpc["management"].null_resource.clean_default_acl[0] Actions: [delete]
- module.landing_zone.module.landing_zone.module.vpc["workload"].null_resource.clean_default_security_group[0] Actions: [delete]
- module.landing_zone.module.landing_zone.module.vpc["workload"].null_resource.clean_default_acl[0] Actions: [delete]

All four of these `null_resource` blocks were retired in the new version of the vpc module, which is why they are marked for destroy in this upgrade.

We will skip upgrade test for this PR.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
