### PR TITLE
feat: base ocp version updated to support v4.16

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

Refer Issue: [Issue-10665](https://github.ibm.com/GoldenEye/issues/issues/10665)
The change is to include the ocp version 4.16

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content
* Support added to include ocp version 4.16 

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Review by ocofaigh — COMMENTED** [review]
@imprateeksh We probably want at least 1 test to deploy 4.16. Usually I would say to just update the default version to 4.16, however its not yet the default for IKS:
image

Until it is, maybe we update 1 test to use 4.16?

**Review by toddgiguere — APPROVED** [review]

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
