### PR TITLE
fix: override json

### PR DESCRIPTION
**Pull request by jor2**
### Description

Value was being overwritten.
https://github.ibm.com/goldeneye/issues/issues/5669

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by jor2** [comment]
A lot of inputs are rendered useless by being overwritten by `override_json_string`. Should we change some of the functionality surrounding this?

**Comment by ocofaigh** [comment]
@toddgiguere Any idea what happened here?

**Comment by toddgiguere** [comment]
That key array in the VSI section tells the VSI which key to use for authentication. The "ssh-keys" string inside the array tells the VSI instance to use the ssh-key with the same identifier that is in another section of the override, that's how it matches the two things up.

By setting the VSI array to empty in the override, will it use the correct key for VSI?

Have we done some testing both ways? (new key vs existing key) Verify that the VSI instances are using the correct key? There is a way in the GUI to verify which auth key is associated with a VSI instance.

**Pull request closed without merging**
