### PR TITLE
fix: scope SLZ s2s auth policies to a resource group

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Scope secret manager auth policy to resource group.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by Aashiq-J** [comment]
@ocofaigh ,
When adding RG for kms <-> block storage, we are still facing this error.
```
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: ╷
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │ Error: The CRN specified in the request is not valid.
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │ 
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │   with module.vsi_landing_zone.module.landing_zone.module.vsi["lvsihp-sepnqs-management-server"].ibm_is_instance.vsi["lvsihp-sepnqs-management-server-2"],
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │   on .terraform/modules/vsi_landing_zone.landing_zone.vsi/main.tf line 87, in resource "ibm_is_instance" "vsi":
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │   87: resource "ibm_is_instance" "vsi" {
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: │ 
TestRunVSIPatternWithHPCS 2023-08-07T10:39:10Z logger.go:66: ╵
```

**Comment by ocofaigh** [comment]
@Aashiq-J The kms <-> block storage auth policy cannot be scoped to a source resource group due to the fact that the Block storage volume does not yet exist in the resource group, so this one has to be left as it is

**Comment by ocofaigh** [comment]
@Aashiq-J What about `cos_to_key_management` and `atracker_to_cos`?

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
