### PR TITLE
landing zone configuration tool updates

### PR DESCRIPTION
**Pull request by KentHall2018**
issue for reference: https://github.ibm.com/Bluemix/docs/issues/10777

@SirSpidey what do you think of these updates?

### Description

content updates for the landing zone configuration tool.

For the patterns/vpc/variables.tf file, can you make "landing zone configuration tool" into a hyperlink that points to https://terraform-ibm-modules.github.io/landing-zone-config-tool/#/home?

### CODE REVIEW

**Comment by SirSpidey** [comment]
@KentHall2018 I created https://github.com/KentHall2018/terraform-ibm-landing-zone/pull/1 to your fork to cover the variables in all the landing zone DAs. When we merge that, it will update this PR.

**Review by SirSpidey — APPROVED** [review]
👍 Any comments from other reviewers or are we good to go?

**Review by toddgiguere — APPROVED** [review]

**Comment by SirSpidey** [comment]
@toddgiguere or @ocofaigh all set to merge?

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
