### PR TITLE
fix: remove the cluster default addons from forced terraform management

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Remove OCP cluster addons that were installed by default from being managed by the terraform `ibm_container_addons` resource.

Before the introduction of the parameter `ibm_container_addons.manage_all_addons` (which this solution defaults to "false"), we needed to include into terraform management the automatically installed `vpc-block-csi-driver`, otherwise it would be removed. We do not need to do this after the introduction of `manage_all_addons` feature, and there now exists more than one auto installed addons which is causing issues with the old logic, so it will be removed.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

OCP v4.15 has an additional addon installed automatically. Due to this change the following fixes have been made to the cluster deployment of this module:
- added the new `ibm-storage-operator` addon to the `addons` input variable list
- removed logic to have this terraform module manage the automatically installed addons for a cluster (such as vpc-block-csi-driver) due to the logic not being required anymore, and also issues in the logic when new auto installed addons are introduced

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Comment by ocofaigh** [comment]
Test failed with:
```
 2024/07/10 20:32:53 Terraform apply |     "Result": {
 2024/07/10 20:32:53 Terraform apply |         "errors": [
 2024/07/10 20:32:53 Terraform apply |             {
 2024/07/10 20:32:53 Terraform apply |                 "code": "vpn_gateway_not_created",
 2024/07/10 20:32:53 Terraform apply |                 "message": "The VPN gateway '02n7-1ae2a957-17b7-4118-9767-405750e27963' could not be created.",
 2024/07/10 20:32:53 Terraform apply |                 "more_info": "https://cloud.ibm.com/docs/infrastructure/vpc/errors.html#vpn_gateway_not_created",
 2024/07/10 20:32:53 Terraform apply |                 "target": {
 2024/07/10 20:32:53 Terraform apply |                     "name": "",
 2024/07/10 20:32:53 Terraform apply |                     "type": ""
 2024/07/10 20:32:53 Terraform apply |                 }
 2024/07/10 20:32:53 Terraform apply |             }
 2024/07/10 20:32:53 Terraform apply |         ],
```

They also failed with this one, but by the time I checked this morning, the resource group was empty, so something is taking longer than usual to get deleted on the backend:
```
Error: [ERROR] Error Deleting resource group: Resource groups with active instances can't be deleted. Use the CLI command "ibmcloud resource service-instances --type all -g <resource-group>" to check for remaining instances, then delete the instances and try again.
```

Upgrade test failed with `The given addon is not provided with upgradable or updatable version` which is expected since this PR has the fix for it, and main branch still has the bug, so I'll skip the upgrade test and retry..

**Comment by toddgiguere** [comment]
I have refactored this code to not remove entirely the `vpc-block-csi-driver` addon from forced management, due to it being destroyed on upgrade which is not intended.

I've simplified this fix by just taking care of the bug of v4.15 having more than one auto-installed addons and the version of `vpc-block-csi-driver` being not found.

The upgrade test is being skipped still, due to the `main` branch will still fail with the bug.

I have done an upgrade test myself between `main` branch and this PR, using OCP v4.14 to avoid the bug, and received "No changes" during the upgrade:
```
 2024/07/11 18:52:17 Terraform plan | 
 2024/07/11 18:52:17 Terraform plan | No changes. Your infrastructure matches the configuration.
 2024/07/11 18:52:17 Terraform plan | 
 2024/07/11 18:52:17 Terraform plan | Terraform has compared your real infrastructure against your configuration
 2024/07/11 18:52:17 Terraform plan | and found no differences, so no changes are needed.
```

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
