### PR TITLE
Removing terraform for VPN gateway connections

### PR DESCRIPTION
**Pull request by kierramarie**
### Description

Support for adding VPN connections is being removed from the override.json as it exposes sensitive values. It will also be removed from subsequent files. Connections will need to manually be added.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Support for VPN gateway connections is being removed. Current connections, if manually made will not be destroyed on upgrade. However, if connections were created with override.json, they will be removed when upgrading to this version.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by kierramarie** [comment]
Addressing [this issue](https://terraform-ibm-modules.github.io/documentation/#/versioning)

**Comment by kierramarie** [comment]
@ocofaigh @toddgiguere let me know what else needs to be done with this.

**Comment by kierramarie** [comment]
The pipeline is failing because some transit gateway connections are being deleted because of the removed terraform block. This is expected. Rerunning skipping the upgrade test.

**Comment by toddgiguere** [comment]
@ocofaigh I asked @kierramarie to verify that we also needed to remove the transit gateway connections, as I saw that was part of this PR as well and couldn't remember if that was also required.

The VPN connection removals looked good though.

**Comment by kierramarie** [comment]
@toddgiguere @ocofaigh I tested it and found that we did not need to remove the transit gateway stuff and have added it back in. if it passes this PR should be good to go.

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
