### PR TITLE
Update prefix var description

### PR DESCRIPTION
**Pull request by SirSpidey**
### Description

- Fix typo (lowerccase) in vsi pattern
- Make prefix descriptions consistent.terraform ini

@toddgiguere: only the `prefix` var in `patterns/roks-quickstart/variables.tf`  has `13` characters. All the rest had `16`. I changed it to 16 but want to make sure that's correct.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
I think 13 is correct for the roks patterns, right @toddgiguere ?

**Review by toddgiguere — DISMISSED** [review]

**Comment by SirSpidey** [comment]
@ocofaigh approved, but not clear on the infra test failures.

**Comment by ocofaigh** [comment]
Pipeline failed with `[ERROR] Create Transit Gateway connection err The requested network is already connected to an existing transit gateway.`

Unrelated to changes in this PR so re-trying..

**Comment by ocofaigh** [comment]
@toddgiguere It failed again with same error `[ERROR] Create Transit Gateway connection err The requested network is already connected to an existing transit gateway.`
Is there an issue in our account? Or did something change on backend??

**Comment by toddgiguere** [comment]
I am still working on narrowing down the issue with transit gateways. If I run the unit tests individually I am getting success, but when the PR tests are run (many in parallel) we get issues with both creation (already exists for this network) and destroy (still has active connections) for the transit gateway resources. During each PR test run most of the tests (but not all) will fail with this, and when testing those same tests individually I do not see the errors.

**Comment by ocofaigh** [comment]
@toddgiguere maybe we should also not provision transite gws in some tests? They are very expensive too, so maybe just have 1 test create one?

**Comment by toddgiguere** [comment]
I have disabled the deployment of transit gateway from all tests except for Quickstart tests. This should provision less gateways in total.

**Comment by toddgiguere** [comment]
Getting a little closer with unit tests. Latest run had three failed tests. Two of them took too long to destroy, and one of them encountered a "Bad Gateway" from cloudflare when executing the API call, none of the errors relate to Transit Gateway.

Will execute again as all three of these issues are hopefully intermittent.

**Comment by ocofaigh** [comment]
The latest test failed when trying to delete subnets:
```
 2024/04/17 13:45:24 Terraform destroy | Error: timeout while waiting for state to become 'done, failed' (last state: 'deleting', timeout: 10m0s)
 2024/04/17 13:45:24 Terraform destroy | 
 2024/04/17 13:45:24 Terraform destroy | 
 2024/04/17 13:45:24 Terraform destroy | Error: timeout while waiting for state to become 'done, failed' (last state: 'deleting', timeout: 10m0s)
```

There is defiantly backend issues impacting us here. I'm going to force merge this PR since its only updating variable descriptions.

**Pull request merged**
