### PR TITLE
fix(deps) update DAs IBM provider version to 1.56.1

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

update DA IBM provider versions to 1.56.1 to pull in fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4755

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Review by toddgiguere — DISMISSED** [review]

**Comment by ocofaigh** [comment]
Thanks @toddgiguere was just looking into the failure :)

**Comment by toddgiguere** [comment]
@ocofaigh I think that was the issue, the examples still set to 1.54 was causing the pre-commit validation to fail. It has now moved on to unit tests.

**Pull request merged**
