### PR TITLE
feat: add expire_rule support for buckets

### PR DESCRIPTION
**Pull request by akocbek**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
We probably want to expose this as variable(s) in each of the patterns too, otherwise consumers of our DAs can't use it. cc @toddgiguere for feedback too

**Review by toddgiguere — APPROVED** [review]
@akocbek @ocofaigh everything looks good in this PR, but we will need to decide what to do with override.json in the future (I think). I can think of 2 ways to keep override.json updated:
1. as we introduce new features through variable properties, we also add them to the sample override files to showcase
2. override.json sample is derived off of the default landing zone configuration, and would match what is produced from a standard deploy in the `config` output

If option 1 is what we want, then we have done this change correctly.

If option 2 is the direction, then we would want to keep the override.json samples in line with the config produced from a standard landing zone deployment

**Comment by ocofaigh** [comment]
Pipeline failed with `Error: [0m Error: [ERROR] Error in getting bucket info rule: Access Denied` - retrying to see if it happens again..

**Pull request merged**
