### PR TITLE
fix: vpc_data output var in patterns vsi module does not give complete output on first apply.

### PR DESCRIPTION
**Pull request by jor2**
### Description

vpc_data: output var in patterns vsi module does not give complete output on first apply
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/777

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

fix for vpc_data: output var in patterns vsi module does not give complete output on first apply.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by jor2** [comment]
> /run pipeline

@surajsbharadwaj we will have a discussion regarding the approach of this pr tomorrow. We don't want to disrupt any outputs.

**Review by toddgiguere — DISMISSED** [review]

**Comment by jor2** [comment]
vpc_data was as below

````
vpc_data = [
  {
    "cidr_blocks" = [
      "10.10.10.0/24",
      "10.30.10.0/24",
      "10.10.30.0/24",
      "10.30.20.0/24",
      "10.20.20.0/24",
      "10.10.20.0/24",
      "10.20.10.0/24",
    ]
    "custom_resolver_hub" = null
    "dns_endpoint_gateways_by_crn" = null
    "dns_endpoint_gateways_by_id" = null
    "network_acls" = [
      {
        "id" = "r010-fb0de8a1-0911-42c3-92dc-e71fc0728fc0"
        "shortname" = "management-t-acl"
      },
    ]
    "public_gateways" = {
      "zone-1" = null
      "zone-2" = null
      "zone-3" = null
    }
    "subnet_detail_list" = {
      "eu-de-1" = {
        "jordan-n-management-t-vpe-zone-1" = {
          "cidr" = "10.10.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
          "id" = "02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
        }
        "jordan-n-management-t-vpn-zone-1" = {
          "cidr" = "10.10.30.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
          "id" = "02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
        }
        "jordan-n-management-t-vsi-zone-1" = {
          "cidr" = "10.10.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
          "id" = "02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
        }
      }
      "eu-de-2" = {
        "jordan-n-management-t-vpe-zone-2" = {
          "cidr" = "10.20.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
          "id" = "02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
        }
        "jordan-n-management-t-vsi-zone-2" = {
          "cidr" = "10.20.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-bee5791d-8655-4838-8947-25dda2776e1e"
          "id" = "02c7-bee5791d-8655-4838-8947-25dda2776e1e"
        }
      }
      "eu-de-3" = {
        "jordan-n-management-t-vpe-zone-3" = {
          "cidr" = "10.30.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
          "id" = "02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
        }
        "jordan-n-management-t-vsi-zone-3" = {
          "cidr" = "10.30.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
          "id" = "02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
        }
      }
    }
    "subnet_detail_map" = {
      "zone-1" = [
        {
          "cidr_block" = "10.10.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
          "id" = "02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
          "zone" = "eu-de-1"
        },
        {
          "cidr_block" = "10.10.30.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
          "id" = "02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
          "zone" = "eu-de-1"
        },
        {
          "cidr_block" = "10.10.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
          "id" = "02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
          "zone" = "eu-de-1"
        },
      ]
      "zone-2" = [
        {
          "cidr_block" = "10.20.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
          "id" = "02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
          "zone" = "eu-de-2"
        },
        {
          "cidr_block" = "10.20.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-bee5791d-8655-4838-8947-25dda2776e1e"
          "id" = "02c7-bee5791d-8655-4838-8947-25dda2776e1e"
          "zone" = "eu-de-2"
        },
      ]
      "zone-3" = [
        {
          "cidr_block" = "10.30.20.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
          "id" = "02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
          "zone" = "eu-de-3"
        },
        {
          "cidr_block" = "10.30.10.0/24"
          "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
          "id" = "02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
          "zone" = "eu-de-3"
        },
      ]
    }
    "subnet_ids" = [
      "02b7-d46a3652-7c7c-4428-a631-6becbb04cb88",
      "02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59",
      "02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85",
      "02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41",
      "02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b",
      "02c7-bee5791d-8655-4838-8947-25dda2776e1e",
      "02d7-2cee76c9-0143-4056-8da2-77716cc297f3",
    ]
    "subnet_zone_list" = [
      {
        "cidr" = "10.10.20.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
        "id" = "02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
        "name" = "jordan-n-management-t-vpe-zone-1"
        "zone" = "eu-de-1"
      },
      {
        "cidr" = "10.20.20.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
        "id" = "02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
        "name" = "jordan-n-management-t-vpe-zone-2"
        "zone" = "eu-de-2"
      },
      {
        "cidr" = "10.30.20.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
        "id" = "02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
        "name" = "jordan-n-management-t-vpe-zone-3"
        "zone" = "eu-de-3"
      },
      {
        "cidr" = "10.10.30.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
        "id" = "02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
        "name" = "jordan-n-management-t-vpn-zone-1"
        "zone" = "eu-de-1"
      },
      {
        "cidr" = "10.10.10.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-1:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
        "id" = "02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
        "name" = "jordan-n-management-t-vsi-zone-1"
        "zone" = "eu-de-1"
      },
      {
        "cidr" = "10.20.10.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-2:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02c7-bee5791d-8655-4838-8947-25dda2776e1e"
        "id" = "02c7-bee5791d-8655-4838-8947-25dda2776e1e"
        "name" = "jordan-n-management-t-vsi-zone-2"
        "zone" = "eu-de-2"
      },
      {
        "cidr" = "10.30.10.0/24"
        "crn" = "crn:v1:bluemix:public:is:eu-de-3:a/abac0df06b644a9cabc6e44f55b3880e::subnet:02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
        "id" = "02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
        "name" = "jordan-n-management-t-vsi-zone-3"
        "zone" = "eu-de-3"
      },
    ]
    "vpc_crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::vpc:r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
    "vpc_data" = {
      "access_tags" = toset([])
      "classic_access" = false
      "crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::vpc:r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
      "cse_source_addresses" = tolist([
        {
          "address" = "10.16.206.123"
          "zone_name" = "eu-de-1"
        },
        {
          "address" = "10.223.40.176"
          "zone_name" = "eu-de-2"
        },
        {
          "address" = "10.223.48.7"
          "zone_name" = "eu-de-3"
        },
      ])
      "default_network_acl" = "r010-d0c808dc-6f91-457a-a074-d9dae3810bef"
      "default_network_acl_crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::network-acl:r010-d0c808dc-6f91-457a-a074-d9dae3810bef"
      "default_network_acl_name" = "python-antibody-jaws-tumble"
      "default_routing_table" = "r010-87531e84-3912-4812-b122-eb4bb931e76f"
      "default_routing_table_name" = "that-agreement-putdown-unfrosted"
      "default_security_group" = "r010-c7a1bf65-f738-4724-8fd7-075de2791e8e"
      "default_security_group_crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::security-group:r010-c7a1bf65-f738-4724-8fd7-075de2791e8e"
      "default_security_group_name" = "snowiness-deltoids-stubble-sloping"
      "dns" = tolist([
        {
          "enable_hub" = false
          "resolution_binding_count" = 0
          "resolver" = tolist([
            {
              "configuration" = "private_resolver"
              "manual_servers" = tolist([])
              "servers" = tolist([
                {
                  "address" = "161.26.0.7"
                  "zone_affinity" = ""
                },
                {
                  "address" = "161.26.0.8"
                  "zone_affinity" = ""
                },
              ])
              "type" = "system"
              "vpc" = tolist([])
            },
          ])
        },
      ])
      "health_reasons" = tolist([])
      "health_state" = "ok"
      "id" = "r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
      "identifier" = "r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
      "name" = "jordan-n-management-t-vpc"
      "resource_controller_url" = "https://cloud.ibm.com/vpc-ext/network/vpcs"
      "resource_crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::vpc:r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
      "resource_group" = "6a3ca6ab799848279aa46cac8b8710df"
      "resource_group_name" = "jordan-n-management-t-rg"
      "resource_name" = "jordan-n-management-t-vpc"
      "resource_status" = "available"
      "security_group" = tolist([
        {
          "group_id" = "r010-42c48293-2833-47fb-8043-5ce81e1d5fc1"
          "group_name" = "jordan-n-management-t"
          "rules" = tolist([
            {
              "code" = 0
              "direction" = "inbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "10.0.0.0/8"
              "rule_id" = "r010-5c0309ef-0c62-4ac0-9ea4-1ccc1a304a8d"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 53
              "port_min" = 53
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-6f1c2e4a-1ef5-454a-bec8-05cfda86b84f"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "10.0.0.0/8"
              "rule_id" = "r010-6c9f5d89-e84e-4724-ac10-a62e1efc6a34"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 443
              "port_min" = 443
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-2c052aae-eb26-49b3-b4ad-8af1626277ba"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "inbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-fb2a999e-1bb5-4b1d-814f-65f9db0ed9fc"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 80
              "port_min" = 80
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-9ad03946-d2f8-4fa2-ae96-6364e7619150"
              "type" = 0
            },
          ])
        },
        {
          "group_id" = "r010-8bab7f11-324e-4e18-a035-7625acada943"
          "group_name" = "management-t-vpe-sg"
          "rules" = tolist([
            {
              "code" = 0
              "direction" = "inbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "10.0.0.0/8"
              "rule_id" = "r010-3efd8b7b-268a-4138-bcd0-187c4e0cc35b"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 443
              "port_min" = 443
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-6f2bafa7-65f2-4536-b08b-bb240f4b4bfc"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "10.0.0.0/8"
              "rule_id" = "r010-bb07d829-8183-44e4-a2f8-d4084cdb824b"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 53
              "port_min" = 53
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-a3ea4f84-6647-429d-af22-1718b76438d5"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "outbound"
              "ip_version" = "ipv4"
              "port_max" = 80
              "port_min" = 80
              "protocol" = "tcp"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-3a4034bd-ca79-4e2c-840a-1d50a8b3c4df"
              "type" = 0
            },
            {
              "code" = 0
              "direction" = "inbound"
              "ip_version" = "ipv4"
              "port_max" = 0
              "port_min" = 0
              "protocol" = "all"
              "remote" = "161.26.0.0/16"
              "rule_id" = "r010-244e124d-d038-43f5-88f6-1099093aff22"
              "type" = 0
            },
          ])
        },
        {
          "group_id" = "r010-c7a1bf65-f738-4724-8fd7-075de2791e8e"
          "group_name" = "snowiness-deltoids-stubble-sloping"
          "rules" = tolist([])
        },
      ])
      "status" = "available"
      "subnets" = tolist([
        {
          "available_ipv4_address_count" = 250
          "id" = "02b7-d46a3652-7c7c-4428-a631-6becbb04cb88"
          "name" = "jordan-n-management-t-vpe-zone-1"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-1"
        },
        {
          "available_ipv4_address_count" = 250
          "id" = "02b7-22e6b2e9-0d17-4cf3-a1ed-eeb84954e56b"
          "name" = "jordan-n-management-t-vsi-zone-1"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-1"
        },
        {
          "available_ipv4_address_count" = 250
          "id" = "02d7-2cee76c9-0143-4056-8da2-77716cc297f3"
          "name" = "jordan-n-management-t-vsi-zone-3"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-3"
        },
        {
          "available_ipv4_address_count" = 250
          "id" = "02c7-bee5791d-8655-4838-8947-25dda2776e1e"
          "name" = "jordan-n-management-t-vsi-zone-2"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-2"
        },
        {
          "available_ipv4_address_count" = 249
          "id" = "02b7-d6f63b6b-4535-4adc-8ae1-0e73cded5c41"
          "name" = "jordan-n-management-t-vpn-zone-1"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-1"
        },
        {
          "available_ipv4_address_count" = 250
          "id" = "02d7-794f2fef-cf7f-43d3-8c41-570d08cdfc85"
          "name" = "jordan-n-management-t-vpe-zone-3"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-3"
        },
        {
          "available_ipv4_address_count" = 250
          "id" = "02c7-0be2d208-b7b0-4e1c-8c9e-b1fd1737ab59"
          "name" = "jordan-n-management-t-vpe-zone-2"
          "status" = "available"
          "total_ipv4_address_count" = 256
          "zone" = "eu-de-2"
        },
      ])
      "tags" = toset([])
    }
    "vpc_flow_logs" = tolist([
      {
        "crn" = "crn:v1:bluemix:public:is:eu-de:a/abac0df06b644a9cabc6e44f55b3880e::flow-log-collector:r010-9cee2279-1ecc-4dd1-9be1-ed2b7f341aae"
        "href" = "https://eu-de.iaas.cloud.ibm.com/v1/flow_log_collectors/r010-9cee2279-1ecc-4dd1-9be1-ed2b7f341aae"
        "id" = "r010-9cee2279-1ecc-4dd1-9be1-ed2b7f341aae"
        "name" = "jordan-n-management-t-logs"
        "state" = "stable"
      },
    ])
    "vpc_id" = "r010-a2ebac92-1963-4658-8d5d-e2ca604c6226"
    "vpc_name" = "jordan-n-management-t-vpc"
  },
]
````

**Comment by jor2** [comment]
@toddgiguere could you merge if only fails are deletion ones pls? Can't check fails as I'm not at my laptop.

**Review by toddgiguere — APPROVED** [review]

**Comment by jor2** [comment]
> /run pipeline

Last run failed on
````
 2024/05/17 16:58:36 Terraform init | Error: Error accessing remote module registry
 2024/05/17 16:58:36 Terraform init | 
 2024/05/17 16:58:36 Terraform init |   on ../../bastion_host.tf line 43:
 2024/05/17 16:58:36 Terraform init |   43: module "bastion_host" {
 2024/05/17 16:58:36 Terraform init | 
 2024/05/17 16:58:36 Terraform init | Failed to retrieve available versions for module "bastion_host"
 2024/05/17 16:58:36 Terraform init | (../../bastion_host.tf:43) from registry.terraform.io: failed to request
 2024/05/17 16:58:36 Terraform init | discovery document: Get
 2024/05/17 16:58:36 Terraform init | "https://registry.terraform.io/.well-known/terraform.json": dial tcp
 2024/05/17 16:58:36 Terraform init | [2600:9000:2646:ac00:16:1aa3:1440:93a1]:443: connect: network is unreachable.
````
Is this not a known issue? @ocofaigh said we will need to force merge as destroy is broken, not sure if this is the issue he mentioned.

**Comment by toddgiguere** [comment]
@jor2 I ran it one more time to see if I can't get it to complete.

@ocofaigh if it is only the cluster destroy that fails, I don't know how to properly force-merge for a release?

**Comment by jor2** [comment]
> @jor2 I ran it one more time to see if I can't get it to complete.
> 
> @ocofaigh if it is only the cluster destroy that fails, I don't know how to properly force-merge for a release?

@toddgiguere `TestRunRoksPatternSchematics` passed this time, but `TestRunOverride` failed for:
````
2024-05-17T19:27:15.2254684Z === NAME  TestRunOverride
2024-05-17T19:27:15.2255164Z     tests.go:827: 
2024-05-17T19:27:15.2256190Z         	Error Trace:	/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.30.2/testhelper/tests.go:827
2024-05-17T19:27:15.2257440Z         	            				/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.30.2/testhelper/tests.go:760
2024-05-17T19:27:15.2258604Z         	            				/__w/terraform-ibm-landing-zone/terraform-ibm-landing-zone/tests/pr_test.go:340
2024-05-17T19:27:15.2259538Z         	Error:      	Expected nil, but got: retry.FatalError{Underlying:(*shell.ErrWithCmdOutput)(0xc0056c4630)}
2024-05-17T19:27:15.2260244Z         	Test:       	TestRunOverride
2024-05-17T19:27:15.2261157Z         	Messages:   	Failed%!(EXTRA retry.FatalError=FatalError{Underlying: error while running command: exit status 1; [31m╷[0m[0m
2024-05-17T19:27:15.2262292Z         	            	[31m│[0m [0m[1m[31mError: [0m[0m[1mcannot add more than 5 gateways to the selected region[0m
2024-05-17T19:27:15.2263013Z         	            	[31m│[0m [0m
2024-05-17T19:27:15.2264059Z         	            	[31m│[0m [0m[0m  with module.landing_zone.module.landing_zone.ibm_tg_gateway.transit_gateway[0],
2024-05-17T19:27:15.2265210Z         	            	[31m│[0m [0m  on ../../transit_gateway.tf line 6, in resource "ibm_tg_gateway" "transit_gateway":
2024-05-17T19:27:15.2266328Z         	            	[31m│[0m [0m   6: resource "ibm_tg_gateway" "transit_gateway" [4m{[0m[0m
2024-05-17T19:27:15.2267013Z         	            	[31m│[0m [0m
2024-05-17T19:27:15.2267426Z         	            	[31m╵[0m[0m})
````
That test passed on last run, we just have too many tg's.

**Comment by jor2** [comment]
Deleted some vpc's i previously provisioned

**Pull request merged**
