### PR TITLE
feat: add support to wait for kms

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Added new var: `kms_wait_for_apply` - support was added in 1.66.0 of provider for this

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Upgrade test failed with expected update:
```
2024-07-02T17:13:19.1279924Z         	Messages:   	Resource(s) identified to be updated 
2024-07-02T17:13:19.1280327Z         	            	Name: cluster
2024-07-02T17:13:19.1281272Z         	            	Address: module.landing_zone.module.landing_zone.ibm_container_vpc_cluster.cluster["rokqsu-wlvken-workload-cluster"]
2024-07-02T17:13:19.1281978Z         	            	Actions: [update]
2024-07-02T17:13:19.1282304Z         	            	DIFF:
2024-07-02T17:13:19.1282685Z         	            	  Before: 
2024-07-02T17:13:19.1283357Z         	            		{"kms_config":"SECURE_VALUE_HIDDEN_HASH:-081ff2b98ae7639aa2cd1e36632a38983baff41b930dc1b8d53ce844"}
2024-07-02T17:13:19.1283934Z         	            	  After: 
2024-07-02T17:13:19.1284596Z         	            		{"kms_config":"SECURE_VALUE_HIDDEN_HASH:-5bd6f77c3188adadd29859535acb955acdad24d05dbb2347577aded4"}
```

No downtime here, so skipping upgrade test and will include the details in the release note

**Comment by ocofaigh** [comment]
Hmm, pipeline failed with `Error: [0m Error: [ERROR] Create Transit Gateway connection err The requested network is already connected to an existing transit gateway.`

Unrelated to changes in this PR, so re-running..

**Review by Aashiq-J — DISMISSED** [review]
LGTM, `kms_wait_for_apply` is added to all required places.

**Comment by ocofaigh** [comment]
@Aashiq-J The schematics test timeout after 60mins, but the workspace apply itself passed, it just took 65 mins. I have updated the timeout value to 90mins, can you please re-review?

**Comment by ocofaigh** [comment]
Hmm, latest run failed with an odd error:
```
 2024/07/03 11:54:46 Terraform apply | Error: [ERROR] Error in getting addons from expandAddOns during Create: [ERROR] The given addon is not provided with upgradable or updatable version
 2024/07/03 11:54:46 Terraform apply | 
 2024/07/03 11:54:46 Terraform apply |   with module.roks_landing_zone.module.landing_zone.ibm_container_addons.addons["ocp-sc-zofgif-workload-cluster"],
 2024/07/03 11:54:46 Terraform apply |   on ../../cluster.tf line 171, in resource "ibm_container_addons" "addons":
 2024/07/03 11:54:46 Terraform apply |  171: resource "ibm_container_addons" "addons" {
 2024/07/03 11:54:46 Terraform apply | 
 2024/07/03 11:54:46 Terraform apply | ---
 2024/07/03 11:54:46 Terraform apply | id: terraform-1c1694c6
 2024/07/03 11:54:46 Terraform apply | summary: '[ERROR] Error in getting addons from expandAddOns during Create:
 2024/07/03 11:54:46 Terraform apply | [ERROR]
 2024/07/03 11:54:46 Terraform apply |   The given addon is not provided with upgradable or updatable version'
 2024/07/03 11:54:46 Terraform apply | severity: error
 2024/07/03 11:54:46 Terraform apply | resource: ibm_container_addons
 2024/07/03 11:54:46 Terraform apply | operation: create
 2024/07/03 11:54:46 Terraform apply | component:
 2024/07/03 11:54:46 Terraform apply |   name: github.com/IBM-Cloud/terraform-provider-ibm
 2024/07/03 11:54:46 Terraform apply |   version: 1.66.0
 2024/07/03 11:54:46 Terraform apply | ---
```

Going to retry..

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
