### PR TITLE
feat: add support for new parameter from base-ocp

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
Waiting for this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/530) to merge.

**Comment by toddgiguere** [comment]
We should also include fix for #888 in this release

**Comment by Aashiq-J** [comment]
@ocofaigh , we need to merge this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/530) first to update the new release version of the base-ocp in this PR

**Comment by Aashiq-J** [comment]
```
2024-09-24T20:57:25.9430013Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m╷[0m[0m
2024-09-24T20:57:25.9435619Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m[1m[31mError: [0m[0m[1mlocal-exec provisioner error[0m
2024-09-24T20:57:25.9441151Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m
2024-09-24T20:57:25.9443693Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m[0m  with module.landing_zone.module.landing_zone.module.cluster["rokqsu-l4dvkh-workload-cluster"].null_resource.reset_api_key,
2024-09-24T20:57:25.9447171Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m  on .terraform/modules/landing_zone.landing_zone.cluster/main.tf line 279, in resource "null_resource" "reset_api_key":
2024-09-24T20:57:25.9449851Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m 279:   provisioner "local-exec" [4m{[0m[0m
2024-09-24T20:57:25.9451694Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m
2024-09-24T20:57:25.9453312Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0mError running command
2024-09-24T20:57:25.9459724Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0m'.terraform/modules/landing_zone.landing_zone.cluster/scripts/reset_iks_api_key.sh
2024-09-24T20:57:25.9462322Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0mau-syd 4369f9da92ce485dac9c858b7748dce2 true default': exit status 28.
2024-09-24T20:57:25.9464298Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m│[0m [0mOutput: 
2024-09-24T20:57:25.9465925Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:25Z logger.go:66: [31m╵[0m[0m
2024-09-24T20:57:25.9478274Z TestRunUpgradeVsiPattern 2024-09-24T20:57:25Z command.go:185: [0m[1mmodule.vsi_landing_zone.module.landing_zone.module.vsi["vsi-u-4ffobk-management-server"].data.ibm_is_vpc.vpc: Read complete after 4s [id=r018-6b1ffec8-9fa9-4483-95d9-77da74aef0bc][0m
2024-09-24T20:57:26.0038749Z TestRunUpgradeROKSQuickStartPattern 2024-09-24T20:57:26Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; [31m╷[0m[0m
2024-09-24T20:57:26.0041330Z [31m│[0m [0m[1m[31mError: [0m[0m[1mlocal-exec provisioner error[0m
2024-09-24T20:57:26.0042337Z [31m│[0m [0m
2024-09-24T20:57:26.0043999Z [31m│[0m [0m[0m  with module.landing_zone.module.landing_zone.module.cluster["rokqsu-l4dvkh-workload-cluster"].null_resource.reset_api_key,
2024-09-24T20:57:26.0046011Z [31m│[0m [0m  on .terraform/modules/landing_zone.landing_zone.cluster/main.tf line 279, in resource "null_resource" "reset_api_key":
2024-09-24T20:57:26.0046974Z [31m│[0m [0m 279:   provisioner "local-exec" [4m{[0m[0m
2024-09-24T20:57:26.0047664Z [31m│[0m [0m
2024-09-24T20:57:26.0048078Z [31m│[0m [0mError running command
2024-09-24T20:57:26.0048721Z [31m│[0m [0m'.terraform/modules/landing_zone.landing_zone.cluster/scripts/reset_iks_api_key.sh
2024-09-24T20:57:26.0050964Z [31m│[0m [0mau-syd 4369f9da92ce485dac9c858b7748dce2 true default': exit status 28.
2024-09-24T20:57:26.0051942Z [31m│[0m [0mOutput: 
2024-09-24T20:57:26.0052619Z [31m╵[0m[0m}
```

 The ROKS Quick start upgrade test runs in github actions and since the default value for `use_ibm_cloud_private_api_endpoints` is `true`, it fails to deploy the main branch code.
 We will have to skip the upgradetest so the changes can fix can be merged to main branch.

**Review by ocofaigh — APPROVED** [review]

**Comment by toddgiguere** [comment]
UpgradeROKSPattern test failed with what looks like intermittent issue during resetting of ROKS api keys? The other ROKS tests did not have this error (including the Quickstart itself).
> .terraform/modules/landing_zone.landing_zone.cluster/scripts/reset_iks_api_key.sh
au-syd f2853769dc5f4d369b8f97e1700eaab7 true default': exit status 28.

**Comment by Aashiq-J** [comment]
> UpgradeROKSPattern test failed with what looks like intermittent issue during resetting of ROKS api keys? The other ROKS tests did not have this error (including the Quickstart itself).
> 
> > .terraform/modules/landing_zone.landing_zone.cluster/scripts/reset_iks_api_key.sh
> > au-syd f2853769dc5f4d369b8f97e1700eaab7 true default': exit status 28.

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/889#issuecomment-2373323550

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
